# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
#
# TRANSPARENT BACGROUND
dynamic_background_opacity yes 
background_opacity 0.95
 
# DISABLE SOUND
enable_audio_bell no
