#!/etc/xdg/picom. conf

backend = "glx";
vsync = true;

# Enable shadows (optional)
shadow = true;

wintypes:
{
	menu        = { shadow = false; };  
	dropdown_menu = { shadow = false; };
	popup_menu    = { shadow = false; };
	utility       = { shadow = false; };
};

