# Open images with Google Chrome
mime ^image, has google-chrome-stable, X, flag f = google-chrome-stable "file://$@"

# Open PDFs with Google Chrome
mime ^application/pdf, has google-chrome-stable, X, flag f = google-chrome-stable "file://$@"

# Open videos with VLC
mime ^video, has vlc, X, flag f = vlc "$@"
ext mp4|mkv|avi|mov|webm, has vlc, X, flag f = vlc "$@"
